stages:
  - build
  - deploy

build:
  stage: build
  image: docker.ekuaibao.com/ci-nodejs
  script:
    - npm --registry http://repo.ekuaibao.com/repository/npm-group/ install
    - npm run build
    - npm run publish2npm
  only:
    - /^v?\d+(\.\d+)+[\.\-_\w]*/
  tags:
    - docker
